import { Command } from "commander";

const TOP_COMMANDS = ["project", "worktree", "session", "agent", "log", "data", "completion"];

const SUBCOMMANDS: Record<string, string[]> = {
  project: ["add", "list", "status", "archive", "remove"],
  worktree: ["add", "list", "remove"],
  session: ["start", "stop", "sync", "list"],
  agent: ["start", "stop", "list"],
  data: ["export", "import"],
  completion: ["bash", "zsh"],
};

function bashScript(): string {
  return `#!/usr/bin/env bash
# context bash completion
# Generated by: context completion bash
# Install: source <(context completion bash)
# Or save to file: context completion bash > /path/to/completion.sh

_context() {
    local cur prev opts subcmds
    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"

    opts="${TOP_COMMANDS.join(" ")} --help --version"

    if [ \${COMP_CWORD} -eq 1 ]; then
        COMPREPLY=( $(compgen -W "\${opts}" -- "\${cur}") )
        return 0
    fi

    case "\${COMP_WORDS[1]}" in
${Object.entries(SUBCOMMANDS)
  .map(
    ([cmd, subs]) => `        ${cmd})
            subcmds="${subs.join(" ")} --help"
            if [ \${COMP_CWORD} -eq 2 ]; then
                COMPREPLY=( $(compgen -W "\${subcmds}" -- "\${cur}") )
                return 0
            fi
            ;;`
  )
  .join("\n")}
    esac
}

complete -F _context context
`;
}

function zshScript(): string {
  return `#!/usr/bin/env zsh
# context zsh completion
# Generated by: context completion zsh
# Install: source <(context completion zsh)
# Or save to a file in \$fpath: context completion zsh > /usr/local/share/zsh/site-functions/_context

#compdef context

_context() {
    local curcontext="\$curcontext" state line
    typeset -A opt_args

    _arguments -C \\
        '1: :->command' \\
        '*:: :->args' \\
        && ret=0

    case \$state in
        command)
            _values 'commands' \\
${TOP_COMMANDS.map((cmd) => `                '${cmd}[${cmdDescription(cmd)}]' \\\n`).join("")}            ;;
        args)
            case \$line[1] in
${Object.entries(SUBCOMMANDS)
  .map(
    ([cmd, subs]) => `                ${cmd})
                    _values 'subcommands' \\
${subs.map((sub) => `                        '${sub}' \\\n`).join("")}                    ;;
`
  )
  .join("")}            esac
            ;;
    esac
}

_context "\$@"
`;
}

function cmdDescription(cmd: string): string {
  const descriptions: Record<string, string> = {
    project: "Manage projects",
    worktree: "Manage git worktrees",
    session: "Manage tmux sessions",
    agent: "Manage agent runs",
    log: "Show timeline of sessions and agent runs",
    data: "Import and export data",
    completion: "Generate shell completion scripts",
  };
  return descriptions[cmd] || cmd;
}

export function setupCompletionCommands(program: Command) {
  program
    .command("completion <shell>")
    .description("Generate shell completion script (bash or zsh)")
    .action((shell: string) => {
      if (shell === "bash") {
        console.log(bashScript());
      } else if (shell === "zsh") {
        console.log(zshScript());
      } else {
        console.error(`Unsupported shell: ${shell}. Use 'bash' or 'zsh'.`);
        process.exit(1);
      }
    });
}
